// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-S18oWXOb_OULpP3uWq0Z5xrb1RLA9Yo',
    appId: '1:248012719518:web:84cd19bb8217108701428f',
    messagingSenderId: '248012719518',
    projectId: 'heat-sync',
    authDomain: 'heat-sync.firebaseapp.com',
    storageBucket: 'heat-sync.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwHU9nfOfK50fbUgaayIqvkeBr8aJfOMs',
    appId: '1:248012719518:android:5afd6874f806702301428f',
    messagingSenderId: '248012719518',
    projectId: 'heat-sync',
    storageBucket: 'heat-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVeViYjXN4kr_SVU0AknVtXiwQWi2u3A',
    appId: '1:248012719518:ios:68570e016ab65ecd01428f',
    messagingSenderId: '248012719518',
    projectId: 'heat-sync',
    storageBucket: 'heat-sync.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );
}
